3PC evaluation: messages and delays
cqfn/degitx pull request #178
Opened 2021-04-16 07:20 UTC by g4s8

For #162 - updated abstract, described steps for 3PC positive case and
counted messages and delays for trivial transaction on generic 3PC impl.

2021-04-16 07:55 UTC, ivanbukhtiyarov approved these changes

2021-04-16 09:05 UTC, IlyaMoskva requested changes

2021-04-16 09:05 UTC, IlyaMoskva commented on reports/3pc-evaluation/3pc-evaluation.tex
> +  In this rpeort we evaluate 3PC and compare it with Paxos-commit to analyze which one is better for
rpeort -> typo

2021-04-16 09:45 UTC, g4s8 commented
@IlyaMoskva thanks, fixed comments and other grammar typos

2021-04-20 09:57 UTC, IlyaMoskva approved these changes
Thank you, @g4s8, looks good for me.

2021-04-20 12:56 UTC, merged