Gitlab protocol report: gitaly node failure info
cqfn/degitx pull request #182
Opened 2021-04-27 15:46 UTC by ivanbukhtiyarov

For https://github.com/cqfn/degitx/issues/179 - added an info about sqlElector working and recovery in case of node failure

2021-04-28 07:53 UTC, IlyaMoskva requested changes
@ivanbukhtiyarov Thanks for the clarification. Please, look at my comments.

2021-04-28 07:53 UTC, IlyaMoskva commented on reports/gitlab-commit-protocol/gitlab-commit-protocol.tex
> +Also very Praefect node periodically performs a health check RPC with a Gitaly node.  Once the health checks are complete, Praefect node does a \textit{SELECT} from \textit{node\_status} table to det
very - every?

2021-04-28 07:53 UTC, IlyaMoskva commented on reports/gitlab-commit-protocol/gitlab-commit-protocol.tex
> +again. This status is stored in the \textit{shard\_primaries} table's \textit{read\_only }column. If it is set, mutator RPCs against the storage shard should be blocked in order to prevent new primar
Please, rewrite this sentence to be unambiguous. Too long and complex to understand right.

2021-04-28 07:53 UTC, IlyaMoskva commented on reports/gitlab-commit-protocol/gitlab-commit-protocol.tex
> +\todo{figure out the process of prefect (TM) backup}
pr**a**efect

2021-04-28 07:53 UTC, IlyaMoskva commented on reports/gitlab-commit-protocol/gitlab-commit-protocol.tex
> +node list, then \textit{sqlElector} updates its internal state to match.
What kind of list - ordered by some sign or not? How system choose which node should be taken from it?

2021-04-28 17:31 UTC, ivanbukhtiyarov commented
Thanks for review @IlyaMoskva, fixed mistakes and tried to clarify primary electing strategy.

2021-04-29 08:55 UTC, IlyaMoskva approved these changes
Great job, @ivanbukhtiyarov

2021-04-30 06:32 UTC, g4s8 approved these changes
@ivanbukhtiyarov thanks

2021-04-30 06:34 UTC, merged