Gitaly
cqfn/degitx pull request #190
Opened 2021-05-25 12:31 UTC by IlyaMoskva

For #162: The first version of Gitaly model.

2021-05-25 14:17 UTC, ChGen commented on reports/3pc-evaluation/Gitaly.tla
> +                await Len(preparedNodes) * 2 > Len(RM) /\ rmState[1] = "prepared"
semicolon symbol is missing on the end of the line (translation error)

2021-05-25 14:17 UTC, ChGen commented on reports/3pc-evaluation/Gitaly.tla
> +                await Len(abortedNodes) * 2 > Len(RM)
semicolon symbol is missing on the end of the line (translation error)

2021-05-25 14:18 UTC, ChGen requested changes
Marked few issues in the code

2021-05-26 12:50 UTC, IlyaMoskva commented on reports/3pc-evaluation/Gitaly.tla
> +\* BEGIN TRANSLATION (chksum(pcal) = "44e2d299" /\ chksum(tla) = "ac2fab31")
fixed

2021-06-01 07:47 UTC, g4s8 approved these changes
@IlyaMoskva thanks

2021-06-01 14:23 UTC, ivanbukhtiyarov approved these changes
@ChGen check please again

2021-06-02 08:52 UTC, ivanbukhtiyarov commented
Test comment

2021-06-02 09:57 UTC, merged