179 gitaly report finalizer
cqfn/degitx pull request #218
Opened 2021-07-01 08:17 UTC by ivanbukhtiyarov

For cqfn#210 and cqfn#179
Complex document refactoring: added intro, virtual storage info, structure refactoring and so on

2021-07-06 05:55 UTC, g4s8 requested changes
@ivanbukhtiyarov please check my comments. Also, I don't see the conclusion in this report: did we find any inconsistency and what are the risks of using this protocol in production

2021-07-06 05:55 UTC, g4s8 commented on reports/gitlab-commit-protocol/gitlab-commit-protocol.tex
> +Despite the fact that the gitaly team claims strong consistency, there are possible cases when inconsistency can occur. The main goals of this technical report are to describe full gitlab  workflow o
Please try to split long lines to multiple linse in `tex` sources, now it's not possible to comment on specific line.

> there are possible cases when inconsistency can occur

Did we really find any "inconsistency"? 

> "git push"

it should be:
```tex
``git push''
```
in sources: double ` - for opening quote, double ' - for closing.

2021-07-06 17:30 UTC, IlyaMoskva approved these changes
This version is good for me. Thanks, @ivanbukhtiyarov .

2021-07-07 07:19 UTC, g4s8 approved these changes
@ivanbukhtiyarov thanks

2021-07-07 07:19 UTC, merged