#76 - reference transaction hook researched
cqfn/degitx pull request #98
Opened 2020-11-27 07:26 UTC by stepanvalyavskiy

#76 - Research for git reference transaction hook.
- Could it be connected with Raft/Paxos? - yes.
- Can it lock on set of ref to allow work with independent ref parallel? - yes.

2020-11-30 07:14 UTC, g4s8 requested changes
@stepanvalyavskiy please check my comment

2020-11-30 07:14 UTC, g4s8 commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@stepanvalyavskiy consensus algorithms can't be implemented with {2,3}PC, see section 7.1 here: https://www.cl.cam.ac.uk/teaching/2021/ConcDisSys/dist-sys-notes.pdf - it's a different algorithms with operations coordinator (always single coordinator not temporary leader) and different logic of accepting (accept changes only if all replicas accepts it, not the consensus)

2020-11-30 07:41 UTC, stepanvalyavskiy commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@g4s8 as I understood from gitaly issues discussions, they accept changes only if a quorum accepts, and schedule replication for others, that didn't accept changes. So it is still the consensus.

> In case it hears from a quorum of Gitaly nodes that they successfully locked the references, it will send back the 
> "commit" message and the Git hook will exist succesfully. In case no quorum is reached, it will send back "abort" to the 
> hooks and cause them to exit with an error, aborting the transaction.
see [2529](https://gitlab.com/gitlab-org/gitaly/-/issues/2529)

2020-11-30 09:01 UTC, g4s8 commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@stepanvalyavskiy but neither Raft or Paxos doesn't have any voting mechanism for accepting changes in replicated log - they just accept everything that leader proposed

2020-11-30 10:06 UTC, stepanvalyavskiy commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@g4s8 Authors use this hook to implement a voting mechanism on operations coordinator for 2/3PC, but they don't force us to do the same. We can choose the other way how to use it.
But I'm agree that using Raft/Paxos is too complex here. I will update this with better description.
Thanks for review.

2020-11-30 13:18 UTC, g4s8 requested changes

2020-11-30 13:18 UTC, g4s8 commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@stepanvalyavskiy can you please fix it, and I'll merge this PR

2020-12-02 07:26 UTC, stepanvalyavskiy commented on white-paper/wp.tex
> +It was designed to implement a voting mechanism and it could be integrated with any consensus algorithm including raft or paxos.
@g4s8 done, please check changes.

2020-12-03 13:43 UTC, g4s8 approved these changes
@stepanvalyavskiy thanks

2021-01-12 12:03 UTC, g4s8 approved these changes
@stepanvalyavskiy thanks

2021-01-12 12:06 UTC, merged